version: "3.8"
services:
  app:
    image: motorcms/motor-headless-php-81-dev:latest
    environment:
      APP_NAME: motor-cms
      APP_URL: localhost
      DB_HOST: mysql
      DB_CONNECTION: mysql
      DB_PORT: 3306
      DB_DATABASE: motor-cms
      DB_USERNAME: user
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PASSWORD: password
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: predis
      REDIS_PORT: 6379
      MEILISEARCH_HOST: meilisearch:7700
      MEILISEARCH_KEY: masterKey
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ./docker-compose/php/custom_php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker-compose/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - motor_network
    depends_on:
      - nginx
      - mysql
      - redis

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - motor_network

  redis:
    image: wodby/redis:6
    environment:
      REDIS_PASSWORD: password
    networks:
      - motor_network
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8-oracle
    restart: always
    environment:
      MYSQL_DATABASE: motor-cms
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-compose/mysql_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - motor_network

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.1.0
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - motor_network
    volumes:
      - ./docker-compose/meilisearch/data.ms:/data.ms
    restart: unless-stopped

volumes:
  mysql:
    external: false
networks:
  motor_network:
    driver: bridge
